version: "3"
services:
  database:
    image: postgres:buster
    container_name: db
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_USER}
      POSTGRES_USER: ${DATABASE_PASS}
      POSTGRES_PASSWORD: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"

  app:
    image: app
    container_name: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"