version: "3"
services:
  database:
    image: postgres:buster
    container_name: db
    env_file:
      - .env
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "./postgresql-data:/var/lib/postgresql/data"

  app:
    image: app
    container_name: app
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    networks:
      - default
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"